### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-anniavdc#1]
Super @anniavdc !!!

Here you have some tips to improve the exercise:

- [x] Improve text in `alt` attributes.
- [x] Be extra careful with CSS syntax, the media query is unclosed.
- [x] Remove orange borders
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Remove unnecessary vertical scroll
- [x] When using rem, remember to indicate the base size on `HTML` tag
- [x] Remove commented CSS rules
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by anniavdc** [comment]
I think the improvements are ready. The alt attributes in this case are only applied to the image, right?

**Comment by anniavdc** [comment]
Sorry I forgot to tag you yesterday @nasivuela

**Comment by nasivuela** [comment]
Well done, and super quick ;)

![](https://media.giphy.com/media/8g63zqQ5RPt60/giphy.gif)

A little detail: check your media queries, seems like you are repeating some rules. Anyway, I consider this done!

**Comment by anniavdc** [comment]
I will thanks :dancer: @nasivuela
